language: node_js
services:
  - docker
node_js:
  - "11"
env:
  - CYPRESS_baseUrl=http://localhost:81
cache: yarn
script:
  - docker-compose up -d
  - yarn wait
  - yarn test:e2e
  - docker-compose down
